### ISSUE TITLE
Not working in background

### ISSUE THREAD

**Issue by sadiq61651** [X-SLAYER/notification_listener_service#2]
Hello dear..
First of all thanks for providing us such a great plugin which listen the incoming calls
it works perfectly when we are in app but when we put the app in background(exit app) so it's doesn't show the actual data instead of actual data it so the following

**D/skia    ( 3443): Encode PNG Singlethread processname=com. :      19276 us, width=189, height=189
W/FlutterJNI( 3443): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: x-slayer/notifications_event. Response ID: 25**

Can u please help me out to solve this issue..

**Comment by X-SLAYER** [comment]
hello, can you provide the background package u did work with? and how u implemented it

**Comment by X-SLAYER** [comment]
i just tested it with this plugin [flutter_foreground_task](https://pub.dev/packages/flutter_foreground_task) and it works very well

**Comment by sadiq61651** [comment]
Can u show an example of it with flutter background task.

Thank u

**Comment by sadiq61651** [comment]
I'm flutter foreeground task

**Comment by sadiq61651** [comment]
Can u show an example of it with flutter foreground task.?

Thank u

**Comment by X-SLAYER** [comment]
a working [example](https://github.com/X-SLAYER/foreground_plugins_test) on the foreground

**Comment by shinewanna** [comment]
Hello guys, after clear the recent, it can't listen anymore.
