### ISSUE TITLE
New Feature Request - Album Art

### ISSUE THREAD

**Issue by eticaretmuhendisi** [X-SLAYER/notification_listener_service#7]
Hi,
I am using a similar plugin in React Native. Among its features is the album art. Can you add the same feature?
RN example: https://github.com/leandrosimoes/react-native-android-notification-listener/issues/21

**Comment by X-SLAYER** [comment]
New version is published [notification_listener_service: ^0.3.2](https://pub.dev/packages/notification_listener_service)
