### ISSUE TITLE
Get App Icon

### ISSUE THREAD

**Issue by toilathor** [X-SLAYER/notification_listener_service#8]
I am using Xiaomi Mi 10
Miui 13.0.7.0
Android 12
i got this error after listening to the notification. I think your library has a problem when taking out the App Icon

### Error!

> W/System.err(19775): android.content.pm.PackageManager$NameNotFoundException: com.facebook.orca
> W/System.err(19775): 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:471)
> W/System.err(19775): 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:460)
> W/System.err(19775): 	at android.app.ApplicationPackageManager.getApplicationIcon(ApplicationPackageManager.java:1614)
> W/System.err(19775): 	at notification.listener.service.NotificationListener.getSmallIcon(NotificationListener.java:83)
> W/System.err(19775): 	at notification.listener.service.NotificationListener.handleNotification(NotificationListener.java:44)
> W/System.err(19775): 	at notification.listener.service.NotificationListener.onNotificationPosted(NotificationListener.java:31)
> W/System.err(19775): 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:444)
> W/System.err(19775): 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2305)
> W/System.err(19775): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> W/System.err(19775): 	at android.os.Looper.loopOnce(Looper.java:210)
> W/System.err(19775): 	at android.os.Looper.loop(Looper.java:299)
> W/System.err(19775): 	at android.app.ActivityThread.main(ActivityThread.java:8293)
> W/System.err(19775): 	at java.lang.reflect.Method.invoke(Native Method)
> W/System.err(19775): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
> W/System.err(19775): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by X-SLAYER** [comment]
i tested it on android 12 and it works fine any steps to reproduce

**Comment by STRENCH0** [comment]
> i tested it on android 12 and it works fine any steps to reproduce

Api 33 on emulator (and also on real pixel 6 pro).
Task handler looks like this:
```
class PushTaskHandler extends TaskHandler {

  StreamSubscription<ServiceNotificationEvent>? _streamSubscription;

  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
    _streamSubscription = NotificationListenerService.notificationsStream
        .listen((event) async {
      log("Current notification: $event");
    });
  }

  @override
  Future<void> onEvent(DateTime timestamp, SendPort? sendPort) async {}

  @override
  Future<void> onDestroy(DateTime timestamp, SendPort? sendPort) async {
    await _streamSubscription?.cancel();
    await FlutterForegroundTask.clearAllData();
    log("PushTask was destroyed", time: DateTime.now());
  }

  @override
  void onButtonPressed(String id) {
    log('onButtonPressed >> $id');
  }
}
```

**Comment by X-SLAYER** [comment]
Did you try the latest version of the app

**Comment by adnankadalayi** [comment]
hey what is the solution for this issue
