### ISSUE TITLE
Don't receive notifications after app restart

### ISSUE THREAD

**Issue by gabriel-munteanu** [X-SLAYER/notification_listener_service#9]
Hi,

I like your plugin and I would like to use it in one of my projects but I have an issue.
After the first run of the app when I request notifications access all things are good(I can even listen for events in a foreground service). After I restart the app, isPermissionGranted() returns true but then I no longer receive notifications. 
 For sure that for the release version the foreground service will run 'forever'  so it will work until the phone is rebooted and the service is started again(I didn't test that yet).
On the other hand, is annoying that during app development, after a restart some part of the code stops working as expected.
My phone is Xiaomi Mi 10 T Lite.

**Comment by gabriel-munteanu** [comment]
It looks like it didn't liked to listen in the main app and in the service at the same time. My bad.

**Comment by Alayers2804** [comment]
can you explain to me @gabriel-munteanu how you solve this problem? because i actually am facing the same issue. do I need to separate the code for listener initialization?

**Comment by gabriel-munteanu** [comment]
As far as I remember I had this issue because I was using this library in the main app code and in the foreground service at the same time. I think that I solved this issue by using it just in the foreground service.
